if(NOT EXISTS "${CST_QT_BIN}/windeployqt.exe")
  message(FATAL_ERROR "windeployqt not found in the selected Qt installation")
endif()
execute_process(COMMAND "${CST_QT_BIN}/qmake.exe" -query QT_VERSION OUTPUT_VARIABLE version OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
if(NOT version STREQUAL "6.11.2")
  message(FATAL_ERROR "Deployment must use Qt 6.11.2")
endif()
execute_process(COMMAND "${CST_QT_BIN}/windeployqt.exe" --release --compiler-runtime --no-translations
  --no-opengl-sw --no-quick-import --no-system-d3d-compiler --dir "${CST_STAGE}" "${CST_STAGE}/cst.exe"
  COMMAND_ERROR_IS_FATAL ANY)
foreach(module Core Gui Widgets Network)
  if(NOT EXISTS "${CST_STAGE}/Qt6${module}.dll")
    message(FATAL_ERROR "Missing deployed Qt6${module}.dll")
  endif()
endforeach()
if(NOT EXISTS "${CST_STAGE}/platforms/qwindows.dll")
  message(FATAL_ERROR "Missing Windows platform plugin")
endif()
file(GLOB forbidden "${CST_STAGE}/Qt6Qml*.dll" "${CST_STAGE}/Qt6WebEngine*.dll")
if(forbidden)
  message(FATAL_ERROR "Unexpected QML or WebEngine dependency")
endif()
