cmake_minimum_required(VERSION 4.4.3)
set(root "${CST_BUILD}/installer")
set(CST_STAGE "${root}/packages/com.cst.app/data")
file(REMOVE_RECURSE "${root}")
file(COPY "${CST_SOURCE}/installer/config" "${CST_SOURCE}/installer/packages" DESTINATION "${root}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${CST_BUILD}" --config Release --prefix "${CST_STAGE}" COMMAND_ERROR_IS_FATAL ANY)
include("${CST_SOURCE}/cmake/DeployQt.cmake")
include("${CST_SOURCE}/cmake/Signing.cmake")
file(GLOB_RECURSE binaries "${CST_STAGE}/*.exe" "${CST_STAGE}/*.dll")
foreach(binary IN LISTS binaries)
  cst_sign("${binary}")
endforeach()
set(creator "${CST_IFW_ROOT}/bin/binarycreator.exe")
if(NOT EXISTS "${creator}")
  message(FATAL_ERROR "Set CST_IFW_ROOT to Qt Installer Framework 4.11.0")
endif()
execute_process(COMMAND "${creator}" --version OUTPUT_VARIABLE version ERROR_VARIABLE version_error RESULT_VARIABLE status)
if(NOT status EQUAL 0 OR NOT "${version}${version_error}" MATCHES "4\\.11\\.0")
  message(FATAL_ERROR "Qt Installer Framework 4.11.0 is required")
endif()
set(suffix "-unsigned")
if(CST_PRODUCTION_SIGNING)
  set(suffix "")
endif()
file(MAKE_DIRECTORY "${CST_BUILD}/packages")
set(installer "${CST_BUILD}/packages/CST-1.0.0-windows-x64${suffix}.exe")
execute_process(COMMAND "${creator}" --offline-only -c "${root}/config/config.xml" -p "${root}/packages" "${installer}" COMMAND_ERROR_IS_FATAL ANY)
cst_sign("${installer}")
message(STATUS "Installer: ${installer}")
